apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lbc
  namespace: argocd
  # Finalizers enable cascading deletes, meaning deleting the app deletes its managed k8s resources.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to. Defaults to 'default'
  project: default

  # Source defines the Git repository configuration where manifests are stored
  source:
    chart: aws-load-balancer-controller
    repoURL: 'https://aws.github.io/eks-charts'
    helm:
      values: |
        clustername: roboshop-dev
        regios: us-east-1
        serviceaccount: 
          create: false
          name: aws-load-balancer-controller
  # Destination defines where the application manifests will be deployed
  destination:
    server: 'https://kubernetes.default.svc' # Deploys to the cluster hosting Argo CD
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 

