apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-drivers
  namespace: argocd
  # Finalizers enable cascading deletes, meaning deleting the app deletes its managed k8s resources.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to. Defaults to 'default'
  project: default

  # Source defines the Git repository configuration where manifests are stored
  source:
    chart: aws-ebs-csi-driver
    repoURL: 'https://kubernetes-sigs.github.io/aws-ebs-csi-driver'
    targetRevision: 2.64.0
    helm:
      values: |
          name: aws-ebs-csi-driver
  # Destination defines where the application manifests will be deployed
  destination:
    server: 'https://kubernetes.default.svc' # Deploys to the cluster hosting Argo CD
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 

